### ISSUE TITLE
move @types/* packages to devDependencies

### ISSUE THREAD

**Issue by amarzavery** [GoogleChrome/chrome-launcher#127]
If they are in dependencies, it enforces packages that depends on chrome-launcher to install the packages with same versions (@types/core-js, @types/rimraf, @types/mkdirp, @types/node and their dependencies).

So please add them as devDependencies.

**Comment by paulirish** [comment]
sounds good. can't remember why they weren't done as devDependencies to begin with. @samccone do you recall?

**Comment by brendankenny** [comment]
It depends on if the types are needed for the external interface, so we'd need to check that. I can't imagine things like mkdirp or rimraf are needed for that, though.

If `@types/node` is needed for dependencies (e.g. we need a `Buffer` as input or output or something), it's common to set its version to `'*'` (or something else very permissive) since it usually doesn't matter too much and conflicts just causes pain downstream (we [override the version in lighthouse](https://github.com/GoogleChrome/lighthouse/blob/6278e121f71053a6f7b28ef3483317d96b52c69b/package.json#L145) for this reason).

**Comment by stephenbe** [comment]
Hi,

Any update on this? It caused me a lot of headache today trying to ignore core-js while using typescript. I finally managed to figure it out, but I would really appreciate it if you guys could add it to devdependencies. (especially core-js that was causing me problems with typescript).

More info here :
https://stackoverflow.com/questions/55836367/typescript-causing-errors-when-i-have-a-npm-dependency-that-adds-types-core-js

**Comment by Hlkz** [comment]
Hi,

Is there any reason why @types/node is still in dependencies and not devDependencies ?

I started to use ts on a module meant for the browser, but it happens to have chrome-launcher as a sub-dependency (for some dev cli purpose), so it also ends having @types/node as a sub-dependency.
Not a big deal, and maybe I don't understand something.
Anyway thanks in advance

**Comment by connorjclark** [comment]
Yes, the explanation is above. https://github.com/GoogleChrome/chrome-launcher/issues/127#issuecomment-427976173

**Comment by Hlkz** [comment]
> Yes, the explanation is above. [#127 (comment)](https://github.com/GoogleChrome/chrome-launcher/issues/127#issuecomment-427976173)

Ups, I missed the notification. Ok thank you, it's clear now, sorry for the trouble!
