### ISSUE TITLE
Snyk: command injection vulnerability

### ISSUE THREAD

**Issue by moltar** [GoogleChrome/chrome-launcher#199]
snyk reports a vulnerability:

https://snyk.io/test/npm/chrome-launcher/0.13.1

**Comment by patrickhulce** [comment]
As mentioned in that same link, the remediation is to upgrade to 0.13.2 which has already been released. There's nothing more for us to do.

**Comment by patrickhulce** [comment]
Looking further into that vulnerability report. It seems like non-sense. 

We use `process.env.HOME` in exactly 1 place: the regex to determine sort order on macOS. In that situation `process.env.HOME` is not *executed* in a shell or anything resembling a shell, and running their repro on macOS in 0.13.1 does not create the malicious file. 

The vuln report claims it is Linux-specific and that it was fixed in 0.13.2. 0.13.2 only escaped env variables for their usage in regex sorting and for `HOME` specifically, only on macOS, not any shell usage (because again we don't actually do that) and not anything on linux, so it seems impossible to have fixed any such behavior even if it were to exist...
