### ISSUE TITLE
How to use default userDataDir on launch?

### ISSUE THREAD

**Issue by molant** [GoogleChrome/chrome-launcher#47]
Is it possible to launch chrome without creating a new `userDataDir`?
From what I read in the documentation I will have to pass the user's current `userDataDir` as part of the launch options but that doesn't look OK to me. The developer will have to detect the platform and user name to generate the right path (`C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default`, `Users/<username>/Library/Application Support/Google/Chrome/Default`, `/home/<username>/.config/google-chrome/default`, for example).

The scenario I have in mind is to easily allow automation of some pages behind authentication if the user is already authenticated in there, for example.

Will you be open to have something to enable this? If so, what would be your preferred option? New parameter?  Special value in `userDataDir` (maybe `default`)?

**Comment by patrickhulce** [comment]
Auto-detection of the user data dir is intriguing and would certainly be useful on occasion. I'd be against having it as the default though as many automation tasks would expect a clean environment rather than assuming the identity of the whoever happened to be running the script. An option with something like `autodetect` seems reasonable. 

Not sure how others might feel about this.

**Comment by molant** [comment]
> I'd be against having it as the default

Yes, it shouldn't be.

Wouldn't chrome use the default if we remove the --user-data-dir parameter?

**Comment by patrickhulce** [comment]
> Wouldn't chrome use the default if we remove the --user-data-dir parameter?

Oh yes! I thought you wanted to also have it returned to you, not just have Chrome use it 👍  even easier then :)

**Comment by molant** [comment]
@patrickhulce there's a PR with the change in #48.
Hope everyone is OK with this.
